# Generated by Django 5.0.4 on 2024-06-26 07:34
# python manage.py makemigrations main_app --name migrate_unique_brands --empty
# because we need to make custom migration

from django.db import migrations


def create_unique_brands(apps, schema_editor):  # Creating custom function
    shoe = apps.get_model("main_app", "Shoe")  # Getting our model 'Shoe'
    unique_brands = apps.get_model("main_app", "UniqueBrands")

    # Getting all unique brands, 'flat' is used if there are nested collections, so it returns only one list
    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()

    unique_brands.objects.bulk_create([unique_brands(brand_name=brand_name) for brand_name in unique_brands_names])

    # for brand_name in unique_brands_names:
    #     # INSERT INTO unique_brands(brand_name) VALUES (brand_name)
    #     unique_brands.create(brand_name=brand_name)


def reverse_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model("main_app", "UniqueBrands")
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        # Adding our functions:
        migrations.RunPython(create_unique_brands, reverse_unique_brands)
    ]
